server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service
  # H2 Database Configuration (Commented out)
  # datasource:
  #   url: jdbc:h2:mem:authdb
  #   driver-class-name: org.h2.Driver
  #   username: sa
  #   password: password
  # jpa:
  #   database-platform: org.hibernate.dialect.H2Dialect
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console

  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/authdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-circular-references: true

jwt:
  secret: your-256-bit-secret-key-here-make-it-long-and-secure-in-production
  expiration: 86400000 # 24 hours in milliseconds