apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  config.js: |
    window.RUNTIME_CONFIG = {
      VITE_AUTH_API_URL: "http://34.131.79.242:31000/auth",
      VITE_TASKS_API_URL: "http://34.131.79.242:32000/tasks"
    };


