services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_AUTH_API_URL=http://auth-service:8081/auth
      - VITE_TASKS_API_URL=http://task-service:8083/tasks
    depends_on:
      - auth-service
      - task-service

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - todo-network

  task-service:
    build:
      context: ./task-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge 