server:
  port: 8083
  servlet:
    context-path: /tasks

spring:
  application:
    name: task-service
  # H2 Database Configuration (Commented out)
  # datasource:
  #   url: jdbc:h2:mem:taskdb
  #   driver-class-name: org.h2.Driver
  #   username: sa
  #   password: password
  # jpa:
  #   database-platform: org.hibernate.dialect.H2Dialect
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console

  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/taskdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

auth:
  service:
    url: http://localhost:8081/auth